import { createFileRoute, Link } from "@tanstack/react-router";
import { PageHeader, SectionHeader } from "@/components/ui/page-header";
import { KpiCard } from "@/components/ui/kpi-card";
import { TrendArea, BarsChart, Donut, TrendLine } from "@/components/charts";
import { StatusBadge } from "@/components/ui/status-badge";
import {
  Receipt, FileWarning, AlertTriangle, CheckCircle2, IndianRupee,
  Droplets, Gauge, Users, UserX,
} from "lucide-react";
import {
  bills, revenueTrend, formatCurrency, formatNumber,
  billingInsightsKpis, monthlyBillingTrend, billsGeneratedByMonth, billingExceptionAnalysis,
  consumptionKpis, consumptionTrend, consumptionByCategory, topConsumersByUsage,
} from "@/mocks/data";

export const Route = createFileRoute("/_app/dashboard/billing")({ component: BillingDashboard });

function BillingDashboard() {
  const recent = bills.slice(0, 6);
  const topUsage = topConsumersByUsage.slice(0, 7);

  return (
    <>
      <PageHeader title="Billing Dashboard" description="Billing performance, consumption behaviour and exception insights." />

      {/* ============== Billing Insights ============== */}
      <SectionHeader title="Billing Insights" description="Bill generation, billed amount, accuracy and exceptions." />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <KpiCard variant="primary" label={billingInsightsKpis.billsGenerated.label} value={formatNumber(billingInsightsKpis.billsGenerated.value)} delta={billingInsightsKpis.billsGenerated.delta} icon={Receipt} sub="Nov 2025" />
        <KpiCard variant="accent" label={billingInsightsKpis.totalBilled.label} value={formatCurrency(billingInsightsKpis.totalBilled.value)} delta={billingInsightsKpis.totalBilled.delta} icon={IndianRupee} />
        <KpiCard variant="success" label={billingInsightsKpis.billingAccuracy.label} value={billingInsightsKpis.billingAccuracy.value + "%"} delta={billingInsightsKpis.billingAccuracy.delta} icon={CheckCircle2} />
        <KpiCard label={billingInsightsKpis.billingExceptions.label} value={formatNumber(billingInsightsKpis.billingExceptions.value)} delta={billingInsightsKpis.billingExceptions.delta} icon={FileWarning} />
      </div>

      <div className="mt-6 grid grid-cols-1 gap-4 lg:grid-cols-3">
        <div className="rounded-xl border bg-card p-5 shadow-card lg:col-span-2">
          <SectionHeader title="Monthly Billing Trend" description="Billed amount vs billing exceptions" />
          <TrendArea data={monthlyBillingTrend} x="month" series={[
            { key: "billed", label: "Billed (₹ Cr)" },
            { key: "exceptions", label: "Exceptions" },
          ]} height={280} />
        </div>
        <div className="rounded-xl border bg-card p-5 shadow-card">
          <SectionHeader title="Bills Generated by Month" />
          <BarsChart data={billsGeneratedByMonth} x="month" series={[{ key: "bills", label: "Bills" }]} height={280} />
        </div>
      </div>

      <div className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-3">
        <div className="rounded-xl border bg-card p-5 shadow-card lg:col-span-2">
          <SectionHeader title="Billing Exception Analysis" description="Breakdown of exceptions by type" />
          <BarsChart data={billingExceptionAnalysis} x="type" series={[{ key: "count", label: "Cases" }]} height={280} />
        </div>
        <div className="rounded-xl border bg-card shadow-card">
          <div className="flex items-center justify-between border-b p-4">
            <p className="text-sm font-semibold">Recent bill generations</p>
            <Link to="/billing/bills" className="text-xs text-primary hover:underline">View all</Link>
          </div>
          <div className="divide-y">
            {recent.map((b) => (
              <div key={b.id} className="flex items-center gap-3 p-3">
                <div className="min-w-0 flex-1">
                  <p className="truncate text-sm font-medium">{b.id}</p>
                  <p className="truncate text-xs text-muted-foreground">{b.customerName} · {b.period}</p>
                </div>
                <StatusBadge status={b.status} />
                <p className="w-20 text-right text-sm font-semibold tabular-nums">{formatCurrency(b.amount)}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ============== Consumption Analytics ============== */}
      <div className="mt-8">
        <SectionHeader title="Consumption Analytics" description="Total, average and exception consumer cohorts." />
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <KpiCard variant="accent" label={consumptionKpis.total.label} value={formatNumber(consumptionKpis.total.value)} delta={consumptionKpis.total.delta} icon={Droplets} sub="Kilolitres" />
        <KpiCard label={consumptionKpis.average.label} value={consumptionKpis.average.value + " KL"} delta={consumptionKpis.average.delta} icon={Gauge} />
        <KpiCard variant="warning" label={consumptionKpis.highConsumers.label} value={formatNumber(consumptionKpis.highConsumers.value)} delta={consumptionKpis.highConsumers.delta} icon={Users} />
        <KpiCard label={consumptionKpis.zeroConsumers.label} value={formatNumber(consumptionKpis.zeroConsumers.value)} delta={consumptionKpis.zeroConsumers.delta} icon={UserX} />
      </div>

      <div className="mt-6 grid grid-cols-1 gap-4 lg:grid-cols-3">
        <div className="rounded-xl border bg-card p-5 shadow-card lg:col-span-2">
          <SectionHeader title="Monthly Consumption Trend" description="Domestic, commercial and common-area usage" />
          <BarsChart data={consumptionTrend} x="month" stacked series={[
            { key: "domestic", label: "Domestic (KL)" },
            { key: "commercial", label: "Commercial (KL)" },
            { key: "common", label: "Common (KL)" },
          ]} height={280} />
        </div>
        <div className="rounded-xl border bg-card p-5 shadow-card">
          <SectionHeader title="Consumption by Category" />
          <Donut data={consumptionByCategory} />
        </div>
      </div>

      <div className="mt-4 rounded-xl border bg-card shadow-card">
        <div className="flex items-center justify-between border-b p-4">
          <div>
            <p className="text-sm font-semibold">Top Consumers by Usage</p>
            <p className="text-xs text-muted-foreground">Highest billed consumption this cycle</p>
          </div>
          <Link to="/analytics/consumption" className="text-xs text-primary hover:underline">Full analytics</Link>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-muted/40 text-xs uppercase tracking-wider text-muted-foreground">
              <tr>
                <th className="px-4 py-2.5 text-left font-medium">Consumer</th>
                <th className="px-4 py-2.5 text-left font-medium">Township</th>
                <th className="px-4 py-2.5 text-left font-medium">Category</th>
                <th className="px-4 py-2.5 text-right font-medium">Consumption (KL)</th>
                <th className="px-4 py-2.5 text-right font-medium">Billed</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {topUsage.map((c) => (
                <tr key={c.id} className="hover:bg-muted/30">
                  <td className="px-4 py-2.5">
                    <p className="font-medium text-foreground">{c.name}</p>
                    <p className="text-xs text-muted-foreground">{c.id} · {c.flat}</p>
                  </td>
                  <td className="px-4 py-2.5 text-muted-foreground">{c.township}</td>
                  <td className="px-4 py-2.5"><StatusBadge status={c.category} /></td>
                  <td className="px-4 py-2.5 text-right font-semibold tabular-nums">{formatNumber(c.consumption)}</td>
                  <td className="px-4 py-2.5 text-right font-semibold tabular-nums">{formatCurrency(c.amount)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
