import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { KpiCard } from "@/components/ui/kpi-card";
import { BarsChart, TrendArea, TrendLine, Donut } from "@/components/charts";
import { StatusBadge } from "@/components/ui/status-badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Download, FileText } from "lucide-react";
import { toast } from "sonner";
import { downloadPdfReport } from "@/lib/pdf-report";
import {
  revenueTrend, consumptionTrend, collectionEfficiencyTrend, townshipComparison,
  outstandingAging, meterHealth, readSuccessTrend, townships, formatCurrency, formatNumber,
  billingInsightsKpis, monthlyBillingTrend, billsGeneratedByMonth, billingExceptionAnalysis,
  consumptionKpis, consumptionByCategory, topConsumersByUsage, highConsumptionConsumers,
  consumerCategories, billingCycles,
} from "@/mocks/data";

export const Route = createFileRoute("/_app/analytics/reports")({ component: Page });

type ReportKey =
  | "billing-summary" | "consumption-analysis" | "billing-exception" | "high-consumption"
  | "revenue" | "consumption" | "water-loss" | "meters";

const REPORTS: { key: ReportKey; label: string; desc: string }[] = [
  { key: "billing-summary", label: "Billing Summary Report", desc: "Bills generated, billed amount, accuracy and exceptions" },
  { key: "consumption-analysis", label: "Consumption Analysis Report", desc: "Monthly trend, category mix and consumer behaviour" },
  { key: "billing-exception", label: "Billing Exception Report", desc: "Exception breakdown and impacted bills" },
  { key: "high-consumption", label: "High Consumption Report", desc: "Top consumers by usage with category breakup" },
  { key: "revenue", label: "Revenue Report", desc: "Billed vs collected, township comparison" },
  { key: "consumption", label: "Consumption Report", desc: "Domestic, commercial, common-area usage" },
  { key: "water-loss", label: "Water Loss / NRW", desc: "Non-revenue water breakdown and trend" },
  { key: "meters", label: "Meter Report", desc: "Fleet health and read success" },
];

const lossBreakdown = [
  { name: "Physical Leakage", value: 6.4, color: "var(--color-critical)" },
  { name: "Apparent (metering)", value: 4.8, color: "var(--color-warning)" },
  { name: "Unauthorized Use", value: 2.1, color: "var(--color-accent)" },
  { name: "Authorized Unbilled", value: 1.5, color: "var(--color-muted-foreground)" },
];

function buildReportPayload(key: ReportKey, label: string, desc: string, filters: Record<string, string>) {
  const meta = { ...filters, Generated: new Date().toLocaleString("en-IN") };
  const common = { title: label, subtitle: desc, meta, filename: `${label}_${Date.now()}` };

  if (key === "billing-summary") {
    return { ...common, sections: [
      { heading: "Summary", paragraph: `${formatNumber(billingInsightsKpis.billsGenerated.value)} bills generated for ${formatCurrency(billingInsightsKpis.totalBilled.value)} with ${billingInsightsKpis.billingAccuracy.value}% accuracy. ${billingInsightsKpis.billingExceptions.value} exceptions recorded.` },
      { heading: "Monthly Billing Trend", table: { head: ["Month", "Billed (₹ Cr)", "Exceptions"], body: monthlyBillingTrend.map((r) => [r.month, r.billed.toFixed(2), r.exceptions]) } },
      { heading: "Bills Generated by Month", table: { head: ["Month", "Bills"], body: billsGeneratedByMonth.map((r) => [r.month, r.bills]) } },
    ] };
  }
  if (key === "consumption-analysis") {
    return { ...common, sections: [
      { heading: "Summary", paragraph: `Total ${formatNumber(consumptionKpis.total.value)} KL · Avg ${consumptionKpis.average.value} KL/consumer · ${consumptionKpis.highConsumers.value} high consumers · ${consumptionKpis.zeroConsumers.value} zero consumption.` },
      { heading: "Monthly Consumption", table: { head: ["Month", "Domestic (KL)", "Commercial (KL)", "Common (KL)"], body: consumptionTrend.map((r) => [r.month, r.domestic, r.commercial, r.common]) } },
      { heading: "Consumption by Category", table: { head: ["Category", "Consumption (KL)"], body: consumptionByCategory.map((r) => [r.name, r.value]) } },
    ] };
  }
  if (key === "billing-exception") {
    return { ...common, sections: [
      { heading: "Summary", paragraph: `${billingExceptionAnalysis.reduce((a, b) => a + b.count, 0)} billing exceptions across ${billingExceptionAnalysis.length} categories.` },
      { heading: "Exception Analysis", table: { head: ["Exception Type", "Count"], body: billingExceptionAnalysis.map((r) => [r.type, r.count]) } },
    ] };
  }
  if (key === "high-consumption") {
    return { ...common, sections: [
      { heading: "Summary", paragraph: `${highConsumptionConsumers.length} consumers flagged with abnormally high usage this cycle.` },
      { heading: "Top High-Usage Consumers", table: { head: ["Consumer", "Township", "Category", "Consumption (KL)", "Billed"], body: highConsumptionConsumers.map((r) => [r.name, r.township, r.category, r.consumption, formatCurrency(r.amount)]) } },
    ] };
  }
  if (key === "revenue") {
    return { ...common, sections: [
      { heading: "Summary", paragraph: `Total billed ${formatCurrency(48_72_30_000)}; outstanding ${formatCurrency(3_84_12_500)}.` },
      { heading: "Billed (last 6 months)", table: { head: ["Month", "Billed (₹ Cr)", "Outstanding (₹ Cr)"], body: revenueTrend.slice(-6).map((r) => [r.month, r.revenue.toFixed(2), r.outstanding.toFixed(2)]) } },
      { heading: "Township Comparison", table: { head: ["Township", "Revenue (₹ L)", "Consumption (KL)"], body: townshipComparison.map((t) => [t.name, t.revenue, t.consumption]) } },
    ] };
  }
  if (key === "consumption") {
    return { ...common, sections: [
      { heading: "Monthly Consumption", table: { head: ["Month", "Domestic (KL)", "Commercial (KL)", "Common (KL)"], body: consumptionTrend.map((r) => [r.month, r.domestic, r.commercial, r.common]) } },
    ] };
  }
  if (key === "water-loss") {
    return { ...common, sections: [
      { heading: "Loss Breakdown", table: { head: ["Category", "Loss %"], body: lossBreakdown.map((r) => [r.name, r.value]) } },
    ] };
  }
  return { ...common, sections: [
    { heading: "Fleet Health", table: { head: ["Status", "Count"], body: meterHealth.map((m) => [m.name, m.value]) } },
    { heading: "Read Success (last 14 days)", table: { head: ["Day", "Success %"], body: readSuccessTrend.map((r) => [r.day, r.success]) } },
  ] };
}

function Page() {
  const [report, setReport] = useState<ReportKey>("billing-summary");
  const [township, setTownship] = useState<string>("all");
  const [category, setCategory] = useState<string>("all");
  const [cycle, setCycle] = useState<string>("all");
  const [from, setFrom] = useState<string>("2025-01-01");
  const [to, setTo] = useState<string>("2025-11-30");

  const meta = useMemo(() => REPORTS.find((r) => r.key === report)!, [report]);
  const townshipLabel = township === "all" ? "All townships" : townships.find((t) => t.id === township)?.name ?? "All townships";
  const filters = {
    "Date Range": `${from} → ${to}`,
    Township: townshipLabel,
    "Consumer Category": category === "all" ? "All categories" : category,
    "Billing Cycle": cycle === "all" ? "All cycles" : cycle,
  };

  const handleExport = () => {
    downloadPdfReport(buildReportPayload(report, meta.label, meta.desc, filters));
    toast.success(`${meta.label} downloaded as PDF`);
  };

  return (
    <>
      <PageHeader
        title="Reports"
        description="Generate billing, consumption and operational reports with flexible filters."
        actions={
          <>
            <Button variant="outline" size="sm" onClick={handleExport}>
              <Download className="mr-1.5 h-4 w-4" /> Download PDF
            </Button>
            <Button size="sm" onClick={() => toast.success(`${meta.label} sent to recipients`)}>
              <FileText className="mr-1.5 h-4 w-4" /> Send now
            </Button>
          </>
        }
      />

      <div className="mb-6 rounded-xl border bg-card p-4 shadow-card">
        <div className="grid gap-3 md:grid-cols-3 lg:grid-cols-6">
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">Report</label>
            <Select value={report} onValueChange={(v) => setReport(v as ReportKey)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {REPORTS.map((r) => (<SelectItem key={r.key} value={r.key}>{r.label}</SelectItem>))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">From</label>
            <Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} />
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">To</label>
            <Input type="date" value={to} onChange={(e) => setTo(e.target.value)} />
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">Township</label>
            <Select value={township} onValueChange={setTownship}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All townships</SelectItem>
                {townships.map((t) => (<SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">Consumer Category</label>
            <Select value={category} onValueChange={setCategory}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All categories</SelectItem>
                {consumerCategories.map((c) => (<SelectItem key={c} value={c}>{c}</SelectItem>))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">Billing Cycle</label>
            <Select value={cycle} onValueChange={setCycle}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All cycles</SelectItem>
                {billingCycles.map((c) => (<SelectItem key={c} value={c}>{c}</SelectItem>))}
              </SelectContent>
            </Select>
          </div>
        </div>
      </div>

      <div className="mb-4">
        <h2 className="text-lg font-semibold text-foreground">{meta.label}</h2>
        <p className="text-xs text-muted-foreground">{meta.desc} · {townshipLabel} · {from} → {to}</p>
      </div>

      {report === "billing-summary" && <BillingSummaryReport />}
      {report === "consumption-analysis" && <ConsumptionAnalysisReport />}
      {report === "billing-exception" && <BillingExceptionReport />}
      {report === "high-consumption" && <HighConsumptionReport />}
      {report === "revenue" && <RevenueReport />}
      {report === "consumption" && <ConsumptionReport />}
      {report === "water-loss" && <WaterLossReport />}
      {report === "meters" && <MetersReport />}
    </>
  );
}

/* =================== New reports =================== */

function BillingSummaryReport() {
  return (
    <div className="space-y-4">
      <div className="grid gap-4 md:grid-cols-4">
        <KpiCard variant="primary" label="Bills Generated" value={formatNumber(billingInsightsKpis.billsGenerated.value)} delta={billingInsightsKpis.billsGenerated.delta} />
        <KpiCard variant="accent" label="Total Billed" value={formatCurrency(billingInsightsKpis.totalBilled.value)} delta={billingInsightsKpis.totalBilled.delta} />
        <KpiCard variant="success" label="Billing Accuracy" value={billingInsightsKpis.billingAccuracy.value + "%"} delta={billingInsightsKpis.billingAccuracy.delta} />
        <KpiCard label="Exceptions" value={formatNumber(billingInsightsKpis.billingExceptions.value)} delta={billingInsightsKpis.billingExceptions.delta} />
      </div>
      <div className="grid gap-4 lg:grid-cols-3">
        <div className="rounded-xl border bg-card p-5 shadow-card lg:col-span-2">
          <h3 className="mb-3 text-sm font-semibold">Monthly Billing Trend</h3>
          <TrendArea data={monthlyBillingTrend} x="month" series={[{ key: "billed", label: "Billed (₹ Cr)" }]} height={280} />
        </div>
        <div className="rounded-xl border bg-card p-5 shadow-card">
          <h3 className="mb-3 text-sm font-semibold">Bills Generated</h3>
          <BarsChart data={billsGeneratedByMonth} x="month" series={[{ key: "bills", label: "Bills" }]} height={280} />
        </div>
      </div>
      <ReportTable
        title="Monthly Billing Summary"
        head={["Month", "Bills Generated", "Billed (₹ Cr)", "Exceptions"]}
        rows={monthlyBillingTrend.map((r, i) => [r.month, formatNumber(billsGeneratedByMonth[i].bills), r.billed.toFixed(2), r.exceptions])}
      />
    </div>
  );
}

function ConsumptionAnalysisReport() {
  return (
    <div className="space-y-4">
      <div className="grid gap-4 md:grid-cols-4">
        <KpiCard variant="accent" label="Total Consumption" value={formatNumber(consumptionKpis.total.value) + " KL"} delta={consumptionKpis.total.delta} />
        <KpiCard label="Avg Consumption" value={consumptionKpis.average.value + " KL"} delta={consumptionKpis.average.delta} />
        <KpiCard variant="warning" label="High Consumers" value={formatNumber(consumptionKpis.highConsumers.value)} delta={consumptionKpis.highConsumers.delta} />
        <KpiCard label="Zero Consumers" value={formatNumber(consumptionKpis.zeroConsumers.value)} delta={consumptionKpis.zeroConsumers.delta} />
      </div>
      <div className="grid gap-4 lg:grid-cols-3">
        <div className="rounded-xl border bg-card p-5 shadow-card lg:col-span-2">
          <h3 className="mb-3 text-sm font-semibold">Monthly Consumption Trend</h3>
          <BarsChart data={consumptionTrend} x="month" stacked series={[
            { key: "domestic", label: "Domestic (KL)" },
            { key: "commercial", label: "Commercial (KL)" },
            { key: "common", label: "Common (KL)" },
          ]} height={280} />
        </div>
        <div className="rounded-xl border bg-card p-5 shadow-card">
          <h3 className="mb-3 text-sm font-semibold">By Category</h3>
          <Donut data={consumptionByCategory} />
        </div>
      </div>
      <ReportTable
        title="Consumption by Category"
        head={["Category", "Consumption (KL)", "% of Total"]}
        rows={(() => {
          const total = consumptionByCategory.reduce((a, b) => a + b.value, 0);
          return consumptionByCategory.map((r) => [r.name, formatNumber(r.value), ((r.value / total) * 100).toFixed(1) + "%"]);
        })()}
      />
    </div>
  );
}

function BillingExceptionReport() {
  const total = billingExceptionAnalysis.reduce((a, b) => a + b.count, 0);
  return (
    <div className="space-y-4">
      <div className="grid gap-4 md:grid-cols-3">
        <KpiCard variant="critical" label="Total Exceptions" value={formatNumber(total)} />
        <KpiCard label="Exception Types" value={billingExceptionAnalysis.length} />
        <KpiCard variant="warning" label="% of Bills" value={((total / billingInsightsKpis.billsGenerated.value) * 100).toFixed(2) + "%"} />
      </div>
      <div className="rounded-xl border bg-card p-5 shadow-card">
        <h3 className="mb-3 text-sm font-semibold">Exception Analysis</h3>
        <BarsChart data={billingExceptionAnalysis} x="type" series={[{ key: "count", label: "Cases" }]} height={300} />
      </div>
      <ReportTable
        title="Exceptions Breakdown"
        head={["Exception Type", "Count", "% of Total"]}
        rows={billingExceptionAnalysis.map((r) => [r.type, r.count, ((r.count / total) * 100).toFixed(1) + "%"])}
      />
    </div>
  );
}

function HighConsumptionReport() {
  return (
    <div className="space-y-4">
      <div className="grid gap-4 md:grid-cols-3">
        <KpiCard variant="warning" label="High-Usage Consumers" value={highConsumptionConsumers.length} />
        <KpiCard label="Total Usage (KL)" value={formatNumber(highConsumptionConsumers.reduce((a, b) => a + b.consumption, 0))} />
        <KpiCard variant="accent" label="Billed (₹)" value={formatCurrency(highConsumptionConsumers.reduce((a, b) => a + b.amount, 0))} />
      </div>
      <div className="rounded-xl border bg-card shadow-card">
        <div className="border-b p-4"><p className="text-sm font-semibold">Top High-Usage Consumers</p></div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-muted/40 text-xs uppercase tracking-wider text-muted-foreground">
              <tr>
                <th className="px-4 py-2.5 text-left font-medium">Consumer</th>
                <th className="px-4 py-2.5 text-left font-medium">Township</th>
                <th className="px-4 py-2.5 text-left font-medium">Category</th>
                <th className="px-4 py-2.5 text-right font-medium">Consumption (KL)</th>
                <th className="px-4 py-2.5 text-right font-medium">Billed</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {highConsumptionConsumers.map((c) => (
                <tr key={c.id} className="hover:bg-muted/30">
                  <td className="px-4 py-2.5"><p className="font-medium text-foreground">{c.name}</p><p className="text-xs text-muted-foreground">{c.id} · {c.flat}</p></td>
                  <td className="px-4 py-2.5 text-muted-foreground">{c.township}</td>
                  <td className="px-4 py-2.5"><StatusBadge status={c.category} /></td>
                  <td className="px-4 py-2.5 text-right font-semibold tabular-nums">{formatNumber(c.consumption)}</td>
                  <td className="px-4 py-2.5 text-right font-semibold tabular-nums">{formatCurrency(c.amount)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

function ReportTable({ title, head, rows }: { title: string; head: string[]; rows: (string | number)[][] }) {
  return (
    <div className="rounded-xl border bg-card shadow-card">
      <div className="border-b p-4"><p className="text-sm font-semibold">{title}</p></div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="bg-muted/40 text-xs uppercase tracking-wider text-muted-foreground">
            <tr>{head.map((h, i) => (<th key={i} className={`px-4 py-2.5 font-medium ${i === 0 ? "text-left" : "text-right"}`}>{h}</th>))}</tr>
          </thead>
          <tbody className="divide-y">
            {rows.map((r, ri) => (
              <tr key={ri} className="hover:bg-muted/30">
                {r.map((cell, ci) => (<td key={ci} className={`px-4 py-2.5 ${ci === 0 ? "text-left font-medium text-foreground" : "text-right tabular-nums"}`}>{cell}</td>))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

/* =================== Existing reports (preserved) =================== */

function RevenueReport() {
  return (
    <div className="space-y-4">
      <div className="grid gap-4 md:grid-cols-4">
        <KpiCard variant="primary" label="Total Billed" value={formatCurrency(48_72_30_000)} delta={12.4} />
        <KpiCard label="Outstanding" value={formatCurrency(3_84_12_500)} delta={-5.6} />
        <KpiCard label="Avg Bill (₹)" value={formatNumber(2_894)} delta={3.1} />
        <KpiCard label="Townships" value={townshipComparison.length} />
      </div>
      <div className="rounded-xl border bg-card p-5 shadow-card">
        <h3 className="mb-3 text-sm font-semibold">Billed Trend</h3>
        <TrendArea data={revenueTrend} x="month" series={[{ key: "revenue", label: "Billed (₹ Cr)" }]} height={280} />
      </div>
      <div className="rounded-xl border bg-card p-5 shadow-card">
        <h3 className="mb-3 text-sm font-semibold">Township Comparison</h3>
        <BarsChart data={townshipComparison} x="name" series={[
          { key: "revenue", label: "Revenue (₹ L)" },
          { key: "consumption", label: "Consumption (KL)" },
        ]} height={280} />
      </div>
    </div>
  );
}

function ConsumptionReport() {
  return (
    <div className="space-y-4">
      <div className="rounded-xl border bg-card p-5 shadow-card">
        <h3 className="mb-3 text-sm font-semibold">Consumption Trend</h3>
        <BarsChart data={consumptionTrend} x="month" stacked series={[
          { key: "domestic", label: "Domestic (KL)" },
          { key: "commercial", label: "Commercial (KL)" },
          { key: "common", label: "Common (KL)" },
        ]} height={300} />
      </div>
    </div>
  );
}

function WaterLossReport() {
  return (
    <div className="space-y-4">
      <div className="grid gap-4 lg:grid-cols-3">
        <div className="rounded-xl border bg-card p-5 shadow-card">
          <h3 className="mb-3 text-sm font-semibold">Loss Breakdown</h3>
          <Donut data={lossBreakdown} />
        </div>
        <div className="rounded-xl border bg-card p-5 shadow-card lg:col-span-2">
          <h3 className="mb-3 text-sm font-semibold">NRW Trend</h3>
          <TrendLine data={collectionEfficiencyTrend.map((d) => ({ ...d, nrw: 22 - d.efficiency * 0.1 }))} x="month" series={[{ key: "nrw", label: "NRW %", color: "var(--color-critical)" }]} height={260} />
        </div>
      </div>
    </div>
  );
}

function MetersReport() {
  return (
    <div className="space-y-4">
      <div className="grid gap-4 lg:grid-cols-3">
        <div className="rounded-xl border bg-card p-5 shadow-card">
          <h3 className="mb-3 text-sm font-semibold">Fleet Health</h3>
          <Donut data={meterHealth} />
        </div>
        <div className="rounded-xl border bg-card p-5 shadow-card lg:col-span-2">
          <h3 className="mb-3 text-sm font-semibold">Read Success Trend</h3>
          <TrendArea data={readSuccessTrend} x="day" series={[{ key: "success", label: "Success", color: "var(--color-success)" }]} height={260} />
        </div>
      </div>
    </div>
  );
}

// Suppress unused warnings for charts kept available to extensions
void outstandingAging;
